language: go

services:
  - docker

go:
  - "1.12"
  - "1.13"
  - "stable"

install:
  - go mod vendor
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/go-playground/overalls

script:
  - make verify
  - make test

after_success:
  - $GOPATH/bin/overalls -project=github.com/vgarvardt/pgx-helpers -covermode=count
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile; fi
